### Get All orders
GET http://localhost:8080/api/orders

### Get single order
GET http://localhost:8080/api/orders/0524663f-a494-4800-a3c5-c41902d28dc8

### Get single order, not existing
GET http://localhost:8080/api/orders/60e84414-3704-4ea7-948c-a4320390652e

### Get customer orders
GET http://localhost:8080/api/customers/284caec3-86d5-4f2e-aecb-6cac35ad3b5f/orders

### Get customer orders, empty
GET http://localhost:8080/api/customers/d4e718ba-aabc-48d1-9ae8-d6f82bd31eb0/orders

### Create new order
PUT http://localhost:8080/api/orders/60e84414-3704-4ea7-948c-a4320390652e
Content-Type: application/json

{
  "orderDate": "2023-11-12",
  "totalAmount": 120.0,
  "customer":"aca2e55b-04a2-4587-b8ef-5a16ffa6cc24"
}

### Delete order
DELETE http://localhost:8080/api/orders/60e84414-3704-4ea7-948c-a4320390652e

### Get all customers
GET http://localhost:8080/api/customers

### Get single customer
GET http://localhost:8080/api/customers/284caec3-86d5-4f2e-aecb-6cac35ad3b5f

### Get single customer not existing
GET http://localhost:8080/api/customers/aca2e55b-04a2-4587-b8ef-5a16ffa6cc23

### Delete customer
DELETE http://localhost:8080/api/customers/aca2e55b-04a2-4587-b8ef-5a16ffa6cc23